name: Node.js CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Forráskód letöltése
        uses: actions/checkout@v5

      - name: Node.js beállítása
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm

      - name: Függőségek telepítése
        run: npm ci

      - name: Tesztek futtatása
        run: npm test
